### ISSUE TITLE
Download page does nothing with large structures

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#118]
**Tool:**
glycam.org/txt. See versions below. Note this is unrelated to the previous bug found with this sequence.

**Bug Description:**
I built a large structure and it gets stuck on the download page "Fetching requested files." No default structure or status is shown. I am able to build other structures that aren't pre-existing. 

**To Reproduce:**

- Go to glycam.org/txt and paste:

DGlcpb1-4DGlcp[6Me]b1-4DGlcp[3Me,6Me]b1-4DGlcpb1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcp[3Me]b1-4DGlcpb1-4DGlcpb1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me]b1-4DGlcp[2Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[2Me]b1-4DGlcp[2Me]b1-4DGlcp[6Me]b1-4DGlcp[2Me]b1-4DGlcp[2Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[3Me,6Me]b1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,6Me]b1-4DGlcpb1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me]b1-4DGlcp[2Me,6Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcp[2Me]b1-4DGlcp[2Me,3Me]b1-4DGlcp[2Me,3Me,6Me]b1-4DGlcpa1-OH

- On options deselect gg, have only tg so there is only 1 structure. 
- Click Generate Selected structures. 

**Screenshots**
Options page, select tg to get down to 1 structure:
![image](https://user-images.githubusercontent.com/17079588/216557510-faf2e230-a146-4f80-86bd-249303c1db7d.png)
Download page is stuck like this for > 3 mins. 
![image](https://user-images.githubusercontent.com/17079588/216557392-4be1808d-7e33-4468-b109-9a790de00cbb.png)

**Device & OS Details**
Firefox on ubuntu.

SITE_MODE:
SWARM
SITE_HOST_NAME:
glycam.org
SITE_CODE_NAME:
yearning-yael
SITE_GIT_BRANCH:
actual
SITE_GIT_COMMIT_HASH:
ce93fc497533f970014478b31182a2c0efd3e33b
GEMS_GIT_BRANCH:
actual
GEMS_GIT_COMMIT_HASH:
a8cf468a9d28e7f6305b109d1c50d31810bec0d5
GMML_GIT_BRANCH:
actual
GMML_GIT_COMMIT_HASH:
35ace0ddc6033de5f187ebb23c9cba4614dea687
MD_UTILS_GIT_BRANCH:
md-test
MD_UTILS_GIT_COMMIT_HASH:
dd4b5c57d82c89f438477987252f90ce63db7ff8
VERSION_DATA_GENERATED:

Fri, 03 Feb 2023 09:07:37 GMT

**Comment by gitoliver** [comment]
Another example is this sequence:

DNeup5Aca2-6DGalpb1-4DGlcpNAcb1-3DGalpb1-4DGlcpNAcb1-3DGalpb1-4DGlcpNAcb1-2DManpa1-6[DNeup5Aca2-6DGalpb1-4DGlcpNAcb1-2DManpa1-3]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH

Deselect down to 16 or so, you'll see the download page is doing nothing, doesn't seem to be polling etc.

**Comment by gitoliver** [comment]
2023-02-07 12:05:08 PM - gemsModules.sequence.receive - ERROR - 1 validation error for sequenceTransactionSchema
project -> indexOrderedSequence
  ensure this value has at most 255 characters (type=value_error.any_str.max_length; limit_value=255)
2023-02-07 12:05:08 PM - gemsModules.sequence.receive - ERROR - Traceback (most recent call last):
  File "/programs/gems/gemsModules/sequence/receive.py", line 62, in receive
    thisTransaction.populate_transaction_in()
  File "/programs/gems/gemsModules/sequence/io.py", line 864, in populate_transaction_in
    self.transaction_in = sequenceTransactionSchema(**self.request_dict)
  File "/programs/gems/gemsModules/sequence/io.py", line 784, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for sequenceTransactionSchema
project -> indexOrderedSequence
  ensure this value has at most 255 characters (type=value_error.any_str.max_length; limit_value=255)

2023-02-07 12:05:08 PM - gemsModules.delegator.receive - ERROR - There was a problem providing the requested service: 'Transaction' object has no attribute 'transaction_out'
2023-02-07 12:05:08 PM - gemsModules.delegator.receive - ERROR - Traceback (most recent call last):
  File "/programs/gems/gemsModules/sequence/receive.py", line 62, in receive
    thisTransaction.populate_transaction_in()
  File "/programs/gems/gemsModules/sequence/io.py", line 864, in populate_transaction_in
    self.transaction_in = sequenceTransactionSchema(**self.request_dict)
  File "/programs/gems/gemsModules/sequence/io.py", line 784, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for sequenceTransactionSchema
project -> indexOrderedSequence
  ensure this value has at most 255 characters (type=value_error.any_str.max_length; limit_value=255)

**Comment by danwentworthart** [comment]
My observations: 
In gems, the project gemsModule is implicated by the above error. 
In the devEnv, there are 2 project gemsModules:
- gems/gemsModules/project
- gems/gemsModuels/deprecated/project

The project under the deprecated folder correctly sets the size limit:
indexOrderedSequence : constr(max_length=65535)=""

By contrast, the project under the gemsModules dir sets the same limit to 255. 

In the devEnv, I see that the deprecated/project/ is the one being used. I will need to hunt down evidence of what is used in production...

**Comment by danwentworthart** [comment]
I believe that in actual, /programs/gems/gemsModules/sequence/io.py is the culprit.
project/io.py CbProject sets indexOrderedSequence to a max_length of 255. 

My theory: if we are comfortable with updating actual to match test, this should resolve.

**Comment by danwentworthart** [comment]
Adding Gray'son to the list of assignees.

**Comment by danwentworthart** [comment]
This is still occurring in both actual and test.
