### ISSUE TITLE
3D Structure Libraries pagination is gone.

### ISSUE THREAD

**Issue by danwentworthart** [GLYCAM-Web/website#154]
**Tool:**
Lib app

**Bug Description:**
No pagination shows on any category

**Expected behavior**
Multiple categories have more than one page. We expect to see page navigation buttons at the bottom of the page. 

**Additional context**
My browser gave the following error: 

`lib.js:56 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at setHrefs (lib.js:56:22)
    at init (lib.js:5:5)
    at chnlib/:869:12
`

**Comment by danwentworthart** [comment]
I was incorrect. The pagination exists and works fine. It simply only comes into play in one category, and I mistakenly expected that there were more categories with multiple pages.

**Comment by danwentworthart** [comment]
Not an issue

**Comment by danwentworthart** [comment]
Not an issue
